package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exadmin;
import com.TestExa.boot.vo.ExadminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExadminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exadmin> selectByExample(ExadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exadmin selectByPrimaryKey(Integer exaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exadmin record, @Param("example") ExadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exadmin record, @Param("example") ExadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exadmin record);
}