package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Examinfo;
import com.TestExa.boot.vo.ExaminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExaminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Examinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Examinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Examinfo> selectByExample(ExaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Examinfo record, @Param("example") ExaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Examinfo record, @Param("example") ExaminfoExample example);
}