package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exoption;
import com.TestExa.boot.vo.ExoptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExoptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exoption> selectByExample(ExoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exoption selectByPrimaryKey(Integer exoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exoption record, @Param("example") ExoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exoption record, @Param("example") ExoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exoption
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exoption record);
}