package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Expaper;
import com.TestExa.boot.vo.ExpaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer expid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Expaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Expaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Expaper> selectByExample(ExpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Expaper selectByPrimaryKey(Integer expid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Expaper record, @Param("example") ExpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Expaper record, @Param("example") ExpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Expaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expaper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Expaper record);
}