package com.TestExa.boot.dao;

import com.TestExa.boot.vo.ExquestionPaper;
import com.TestExa.boot.vo.ExquestionPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExquestionPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExquestionPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExquestionPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(ExquestionPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(ExquestionPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<ExquestionPaper> selectByExample(ExquestionPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ExquestionPaper record, @Param("example") ExquestionPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exquestion_paper
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") ExquestionPaper record, @Param("example") ExquestionPaperExample example);
}