package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exscore;
import com.TestExa.boot.vo.ExscoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExscoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exscid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exscore> selectByExample(ExscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exscore selectByPrimaryKey(Integer exscid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exscore record, @Param("example") ExscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exscore record, @Param("example") ExscoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exscore record);
}