package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exschool;
import com.TestExa.boot.vo.ExschoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExschoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExschoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExschoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exschool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exschool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exschool> selectByExample(ExschoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exschool selectByPrimaryKey(Integer exsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exschool record, @Param("example") ExschoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exschool record, @Param("example") ExschoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exschool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exschool
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exschool record);
}