package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exstudent;
import com.TestExa.boot.vo.ExstudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExstudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExstudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExstudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exstuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exstudent> selectByExample(ExstudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exstudent selectByPrimaryKey(Integer exstuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exstudent record, @Param("example") ExstudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exstudent record, @Param("example") ExstudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exstudent record);
}