package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exsubject;
import com.TestExa.boot.vo.ExsubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExsubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer exsubid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exsubject> selectByExample(ExsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exsubject selectByPrimaryKey(Integer exsubid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exsubject record, @Param("example") ExsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exsubject record, @Param("example") ExsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exsubject
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exsubject record);
}