package com.TestExa.boot.dao;

import com.TestExa.boot.vo.Exteacher;
import com.TestExa.boot.vo.ExteacherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExteacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    long countByExample(ExteacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByExample(ExteacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int deleteByPrimaryKey(Integer extid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insert(Exteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int insertSelective(Exteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    List<Exteacher> selectByExample(ExteacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    Exteacher selectByPrimaryKey(Integer extid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Exteacher record, @Param("example") ExteacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByExample(@Param("record") Exteacher record, @Param("example") ExteacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKeySelective(Exteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    int updateByPrimaryKey(Exteacher record);
}