package com.TestExa.boot.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExadminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public ExadminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andExaidIsNull() {
            addCriterion("exaid is null");
            return (Criteria) this;
        }

        public Criteria andExaidIsNotNull() {
            addCriterion("exaid is not null");
            return (Criteria) this;
        }

        public Criteria andExaidEqualTo(Integer value) {
            addCriterion("exaid =", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidNotEqualTo(Integer value) {
            addCriterion("exaid <>", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidGreaterThan(Integer value) {
            addCriterion("exaid >", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exaid >=", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidLessThan(Integer value) {
            addCriterion("exaid <", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidLessThanOrEqualTo(Integer value) {
            addCriterion("exaid <=", value, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidIn(List<Integer> values) {
            addCriterion("exaid in", values, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidNotIn(List<Integer> values) {
            addCriterion("exaid not in", values, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidBetween(Integer value1, Integer value2) {
            addCriterion("exaid between", value1, value2, "exaid");
            return (Criteria) this;
        }

        public Criteria andExaidNotBetween(Integer value1, Integer value2) {
            addCriterion("exaid not between", value1, value2, "exaid");
            return (Criteria) this;
        }

        public Criteria andExanameIsNull() {
            addCriterion("exaname is null");
            return (Criteria) this;
        }

        public Criteria andExanameIsNotNull() {
            addCriterion("exaname is not null");
            return (Criteria) this;
        }

        public Criteria andExanameEqualTo(String value) {
            addCriterion("exaname =", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameNotEqualTo(String value) {
            addCriterion("exaname <>", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameGreaterThan(String value) {
            addCriterion("exaname >", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameGreaterThanOrEqualTo(String value) {
            addCriterion("exaname >=", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameLessThan(String value) {
            addCriterion("exaname <", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameLessThanOrEqualTo(String value) {
            addCriterion("exaname <=", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameLike(String value) {
            addCriterion("exaname like", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameNotLike(String value) {
            addCriterion("exaname not like", value, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameIn(List<String> values) {
            addCriterion("exaname in", values, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameNotIn(List<String> values) {
            addCriterion("exaname not in", values, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameBetween(String value1, String value2) {
            addCriterion("exaname between", value1, value2, "exaname");
            return (Criteria) this;
        }

        public Criteria andExanameNotBetween(String value1, String value2) {
            addCriterion("exaname not between", value1, value2, "exaname");
            return (Criteria) this;
        }

        public Criteria andExapwdIsNull() {
            addCriterion("exapwd is null");
            return (Criteria) this;
        }

        public Criteria andExapwdIsNotNull() {
            addCriterion("exapwd is not null");
            return (Criteria) this;
        }

        public Criteria andExapwdEqualTo(String value) {
            addCriterion("exapwd =", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdNotEqualTo(String value) {
            addCriterion("exapwd <>", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdGreaterThan(String value) {
            addCriterion("exapwd >", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdGreaterThanOrEqualTo(String value) {
            addCriterion("exapwd >=", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdLessThan(String value) {
            addCriterion("exapwd <", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdLessThanOrEqualTo(String value) {
            addCriterion("exapwd <=", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdLike(String value) {
            addCriterion("exapwd like", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdNotLike(String value) {
            addCriterion("exapwd not like", value, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdIn(List<String> values) {
            addCriterion("exapwd in", values, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdNotIn(List<String> values) {
            addCriterion("exapwd not in", values, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdBetween(String value1, String value2) {
            addCriterion("exapwd between", value1, value2, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExapwdNotBetween(String value1, String value2) {
            addCriterion("exapwd not between", value1, value2, "exapwd");
            return (Criteria) this;
        }

        public Criteria andExasexIsNull() {
            addCriterion("exasex is null");
            return (Criteria) this;
        }

        public Criteria andExasexIsNotNull() {
            addCriterion("exasex is not null");
            return (Criteria) this;
        }

        public Criteria andExasexEqualTo(String value) {
            addCriterion("exasex =", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexNotEqualTo(String value) {
            addCriterion("exasex <>", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexGreaterThan(String value) {
            addCriterion("exasex >", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexGreaterThanOrEqualTo(String value) {
            addCriterion("exasex >=", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexLessThan(String value) {
            addCriterion("exasex <", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexLessThanOrEqualTo(String value) {
            addCriterion("exasex <=", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexLike(String value) {
            addCriterion("exasex like", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexNotLike(String value) {
            addCriterion("exasex not like", value, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexIn(List<String> values) {
            addCriterion("exasex in", values, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexNotIn(List<String> values) {
            addCriterion("exasex not in", values, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexBetween(String value1, String value2) {
            addCriterion("exasex between", value1, value2, "exasex");
            return (Criteria) this;
        }

        public Criteria andExasexNotBetween(String value1, String value2) {
            addCriterion("exasex not between", value1, value2, "exasex");
            return (Criteria) this;
        }

        public Criteria andExabirthIsNull() {
            addCriterion("exabirth is null");
            return (Criteria) this;
        }

        public Criteria andExabirthIsNotNull() {
            addCriterion("exabirth is not null");
            return (Criteria) this;
        }

        public Criteria andExabirthEqualTo(Date value) {
            addCriterionForJDBCDate("exabirth =", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("exabirth <>", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthGreaterThan(Date value) {
            addCriterionForJDBCDate("exabirth >", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exabirth >=", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthLessThan(Date value) {
            addCriterionForJDBCDate("exabirth <", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exabirth <=", value, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthIn(List<Date> values) {
            addCriterionForJDBCDate("exabirth in", values, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("exabirth not in", values, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exabirth between", value1, value2, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExabirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exabirth not between", value1, value2, "exabirth");
            return (Criteria) this;
        }

        public Criteria andExatelIsNull() {
            addCriterion("exatel is null");
            return (Criteria) this;
        }

        public Criteria andExatelIsNotNull() {
            addCriterion("exatel is not null");
            return (Criteria) this;
        }

        public Criteria andExatelEqualTo(String value) {
            addCriterion("exatel =", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelNotEqualTo(String value) {
            addCriterion("exatel <>", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelGreaterThan(String value) {
            addCriterion("exatel >", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelGreaterThanOrEqualTo(String value) {
            addCriterion("exatel >=", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelLessThan(String value) {
            addCriterion("exatel <", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelLessThanOrEqualTo(String value) {
            addCriterion("exatel <=", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelLike(String value) {
            addCriterion("exatel like", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelNotLike(String value) {
            addCriterion("exatel not like", value, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelIn(List<String> values) {
            addCriterion("exatel in", values, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelNotIn(List<String> values) {
            addCriterion("exatel not in", values, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelBetween(String value1, String value2) {
            addCriterion("exatel between", value1, value2, "exatel");
            return (Criteria) this;
        }

        public Criteria andExatelNotBetween(String value1, String value2) {
            addCriterion("exatel not between", value1, value2, "exatel");
            return (Criteria) this;
        }

        public Criteria andExaemailIsNull() {
            addCriterion("exaemail is null");
            return (Criteria) this;
        }

        public Criteria andExaemailIsNotNull() {
            addCriterion("exaemail is not null");
            return (Criteria) this;
        }

        public Criteria andExaemailEqualTo(String value) {
            addCriterion("exaemail =", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailNotEqualTo(String value) {
            addCriterion("exaemail <>", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailGreaterThan(String value) {
            addCriterion("exaemail >", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailGreaterThanOrEqualTo(String value) {
            addCriterion("exaemail >=", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailLessThan(String value) {
            addCriterion("exaemail <", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailLessThanOrEqualTo(String value) {
            addCriterion("exaemail <=", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailLike(String value) {
            addCriterion("exaemail like", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailNotLike(String value) {
            addCriterion("exaemail not like", value, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailIn(List<String> values) {
            addCriterion("exaemail in", values, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailNotIn(List<String> values) {
            addCriterion("exaemail not in", values, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailBetween(String value1, String value2) {
            addCriterion("exaemail between", value1, value2, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaemailNotBetween(String value1, String value2) {
            addCriterion("exaemail not between", value1, value2, "exaemail");
            return (Criteria) this;
        }

        public Criteria andExaaddrIsNull() {
            addCriterion("exaaddr is null");
            return (Criteria) this;
        }

        public Criteria andExaaddrIsNotNull() {
            addCriterion("exaaddr is not null");
            return (Criteria) this;
        }

        public Criteria andExaaddrEqualTo(String value) {
            addCriterion("exaaddr =", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrNotEqualTo(String value) {
            addCriterion("exaaddr <>", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrGreaterThan(String value) {
            addCriterion("exaaddr >", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrGreaterThanOrEqualTo(String value) {
            addCriterion("exaaddr >=", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrLessThan(String value) {
            addCriterion("exaaddr <", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrLessThanOrEqualTo(String value) {
            addCriterion("exaaddr <=", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrLike(String value) {
            addCriterion("exaaddr like", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrNotLike(String value) {
            addCriterion("exaaddr not like", value, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrIn(List<String> values) {
            addCriterion("exaaddr in", values, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrNotIn(List<String> values) {
            addCriterion("exaaddr not in", values, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrBetween(String value1, String value2) {
            addCriterion("exaaddr between", value1, value2, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExaaddrNotBetween(String value1, String value2) {
            addCriterion("exaaddr not between", value1, value2, "exaaddr");
            return (Criteria) this;
        }

        public Criteria andExsidIsNull() {
            addCriterion("exsid is null");
            return (Criteria) this;
        }

        public Criteria andExsidIsNotNull() {
            addCriterion("exsid is not null");
            return (Criteria) this;
        }

        public Criteria andExsidEqualTo(Integer value) {
            addCriterion("exsid =", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotEqualTo(Integer value) {
            addCriterion("exsid <>", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThan(Integer value) {
            addCriterion("exsid >", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exsid >=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThan(Integer value) {
            addCriterion("exsid <", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThanOrEqualTo(Integer value) {
            addCriterion("exsid <=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidIn(List<Integer> values) {
            addCriterion("exsid in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotIn(List<Integer> values) {
            addCriterion("exsid not in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidBetween(Integer value1, Integer value2) {
            addCriterion("exsid between", value1, value2, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotBetween(Integer value1, Integer value2) {
            addCriterion("exsid not between", value1, value2, "exsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exadmin
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exadmin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}