package com.TestExa.boot.vo;

import java.util.Date;

public class Exadmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exaname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exapwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exapwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exasex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exasex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exabirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exabirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exatel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exatel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exaemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exaemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exaaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exaaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exadmin.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exaid
     *
     * @return the value of exadmin.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExaid() {
        return exaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exaid
     *
     * @param exaid the value for exadmin.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExaid(Integer exaid) {
        this.exaid = exaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exaname
     *
     * @return the value of exadmin.exaname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExaname() {
        return exaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exaname
     *
     * @param exaname the value for exadmin.exaname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExaname(String exaname) {
        this.exaname = exaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exapwd
     *
     * @return the value of exadmin.exapwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExapwd() {
        return exapwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exapwd
     *
     * @param exapwd the value for exadmin.exapwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExapwd(String exapwd) {
        this.exapwd = exapwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exasex
     *
     * @return the value of exadmin.exasex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExasex() {
        return exasex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exasex
     *
     * @param exasex the value for exadmin.exasex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExasex(String exasex) {
        this.exasex = exasex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exabirth
     *
     * @return the value of exadmin.exabirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExabirth() {
        return exabirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exabirth
     *
     * @param exabirth the value for exadmin.exabirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExabirth(Date exabirth) {
        this.exabirth = exabirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exatel
     *
     * @return the value of exadmin.exatel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExatel() {
        return exatel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exatel
     *
     * @param exatel the value for exadmin.exatel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExatel(String exatel) {
        this.exatel = exatel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exaemail
     *
     * @return the value of exadmin.exaemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExaemail() {
        return exaemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exaemail
     *
     * @param exaemail the value for exadmin.exaemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExaemail(String exaemail) {
        this.exaemail = exaemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exaaddr
     *
     * @return the value of exadmin.exaaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExaaddr() {
        return exaaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exaaddr
     *
     * @param exaaddr the value for exadmin.exaaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExaaddr(String exaaddr) {
        this.exaaddr = exaaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exadmin.exsid
     *
     * @return the value of exadmin.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exadmin.exsid
     *
     * @param exsid the value for exadmin.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }
}