package com.TestExa.boot.vo;

import java.util.Date;

public class Examinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exstuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.exrecord
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.startime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date startime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.endtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examinfo.sparetime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer sparetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.exstuid
     *
     * @return the value of examinfo.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExstuid() {
        return exstuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.exstuid
     *
     * @param exstuid the value for examinfo.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuid(Integer exstuid) {
        this.exstuid = exstuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.expid
     *
     * @return the value of examinfo.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.expid
     *
     * @param expid the value for examinfo.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.exrecord
     *
     * @return the value of examinfo.exrecord
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExrecord() {
        return exrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.exrecord
     *
     * @param exrecord the value for examinfo.exrecord
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExrecord(String exrecord) {
        this.exrecord = exrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.startime
     *
     * @return the value of examinfo.startime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getStartime() {
        return startime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.startime
     *
     * @param startime the value for examinfo.startime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setStartime(Date startime) {
        this.startime = startime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.endtime
     *
     * @return the value of examinfo.endtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.endtime
     *
     * @param endtime the value for examinfo.endtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examinfo.sparetime
     *
     * @return the value of examinfo.sparetime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getSparetime() {
        return sparetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examinfo.sparetime
     *
     * @param sparetime the value for examinfo.sparetime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setSparetime(Integer sparetime) {
        this.sparetime = sparetime;
    }
}