package com.TestExa.boot.vo;

public class Exanswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exanswer.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exanswer.exainfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exainfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exanswer.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exanswer.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exanswer.exaid
     *
     * @return the value of exanswer.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExaid() {
        return exaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exanswer.exaid
     *
     * @param exaid the value for exanswer.exaid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExaid(Integer exaid) {
        this.exaid = exaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exanswer.exainfo
     *
     * @return the value of exanswer.exainfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExainfo() {
        return exainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exanswer.exainfo
     *
     * @param exainfo the value for exanswer.exainfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExainfo(String exainfo) {
        this.exainfo = exainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exanswer.exqid
     *
     * @return the value of exanswer.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExqid() {
        return exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exanswer.exqid
     *
     * @param exqid the value for exanswer.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExqid(Integer exqid) {
        this.exqid = exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exanswer.expid
     *
     * @return the value of exanswer.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exanswer.expid
     *
     * @param expid the value for exanswer.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }
}