package com.TestExa.boot.vo;

public class Exoption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exoption.exoid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exoption.exop
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exoption.exoinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exoinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exoption.exoindex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exoindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exoption.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exqid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exoption.exoid
     *
     * @return the value of exoption.exoid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExoid() {
        return exoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exoption.exoid
     *
     * @param exoid the value for exoption.exoid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExoid(Integer exoid) {
        this.exoid = exoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exoption.exop
     *
     * @return the value of exoption.exop
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExop() {
        return exop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exoption.exop
     *
     * @param exop the value for exoption.exop
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExop(Integer exop) {
        this.exop = exop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exoption.exoinfo
     *
     * @return the value of exoption.exoinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExoinfo() {
        return exoinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exoption.exoinfo
     *
     * @param exoinfo the value for exoption.exoinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExoinfo(String exoinfo) {
        this.exoinfo = exoinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exoption.exoindex
     *
     * @return the value of exoption.exoindex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExoindex() {
        return exoindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exoption.exoindex
     *
     * @param exoindex the value for exoption.exoindex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExoindex(Integer exoindex) {
        this.exoindex = exoindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exoption.exqid
     *
     * @return the value of exoption.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExqid() {
        return exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exoption.exqid
     *
     * @param exqid the value for exoption.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExqid(Integer exqid) {
        this.exqid = exqid;
    }
}