package com.TestExa.boot.vo;

import java.util.Date;

public class Expaper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.expdata
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date expdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expaper.exptime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.expid
     *
     * @return the value of expaper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.expid
     *
     * @param expid the value for expaper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.exstime
     *
     * @return the value of expaper.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExstime() {
        return exstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.exstime
     *
     * @param exstime the value for expaper.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstime(Date exstime) {
        this.exstime = exstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.exteid
     *
     * @return the value of expaper.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExteid() {
        return exteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.exteid
     *
     * @param exteid the value for expaper.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExteid(Integer exteid) {
        this.exteid = exteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.exsid
     *
     * @return the value of expaper.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.exsid
     *
     * @param exsid the value for expaper.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.expdata
     *
     * @return the value of expaper.expdata
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExpdata() {
        return expdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.expdata
     *
     * @param expdata the value for expaper.expdata
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpdata(Date expdata) {
        this.expdata = expdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expaper.exptime
     *
     * @return the value of expaper.exptime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExptime() {
        return exptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expaper.exptime
     *
     * @param exptime the value for expaper.exptime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExptime(Date exptime) {
        this.exptime = exptime;
    }
}