package com.TestExa.boot.vo;

public class ExquestionPaper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestion_paper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestion_paper.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exqid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestion_paper.expid
     *
     * @return the value of exquestion_paper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestion_paper.expid
     *
     * @param expid the value for exquestion_paper.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestion_paper.exqid
     *
     * @return the value of exquestion_paper.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExqid() {
        return exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestion_paper.exqid
     *
     * @param exqid the value for exquestion_paper.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExqid(Integer exqid) {
        this.exqid = exqid;
    }
}