package com.TestExa.boot.vo;

public class Exquestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestions.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestions.exqinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exqinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestions.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer extid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestions.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exquestions.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsubid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestions.exqid
     *
     * @return the value of exquestions.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExqid() {
        return exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestions.exqid
     *
     * @param exqid the value for exquestions.exqid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExqid(Integer exqid) {
        this.exqid = exqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestions.exqinfo
     *
     * @return the value of exquestions.exqinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExqinfo() {
        return exqinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestions.exqinfo
     *
     * @param exqinfo the value for exquestions.exqinfo
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExqinfo(String exqinfo) {
        this.exqinfo = exqinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestions.extid
     *
     * @return the value of exquestions.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExtid() {
        return extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestions.extid
     *
     * @param extid the value for exquestions.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtid(Integer extid) {
        this.extid = extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestions.expid
     *
     * @return the value of exquestions.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestions.expid
     *
     * @param expid the value for exquestions.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exquestions.exsubid
     *
     * @return the value of exquestions.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsubid() {
        return exsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exquestions.exsubid
     *
     * @param exsubid the value for exquestions.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsubid(Integer exsubid) {
        this.exsubid = exsubid;
    }
}