package com.TestExa.boot.vo;

import java.util.Date;

public class Exscore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exscore.exscid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exscid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exscore.exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exscore.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exscore.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer expid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exscore.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exstuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exscore.exscid
     *
     * @return the value of exscore.exscid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExscid() {
        return exscid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exscore.exscid
     *
     * @param exscid the value for exscore.exscid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExscid(Integer exscid) {
        this.exscid = exscid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exscore.exscore
     *
     * @return the value of exscore.exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExscore() {
        return exscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exscore.exscore
     *
     * @param exscore the value for exscore.exscore
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExscore(Integer exscore) {
        this.exscore = exscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exscore.exstime
     *
     * @return the value of exscore.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExstime() {
        return exstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exscore.exstime
     *
     * @param exstime the value for exscore.exstime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstime(Date exstime) {
        this.exstime = exstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exscore.expid
     *
     * @return the value of exscore.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exscore.expid
     *
     * @param expid the value for exscore.expid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExpid(Integer expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exscore.exstuid
     *
     * @return the value of exscore.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExstuid() {
        return exstuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exscore.exstuid
     *
     * @param exstuid the value for exscore.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuid(Integer exstuid) {
        this.exstuid = exstuid;
    }
}