package com.TestExa.boot.vo;

public class Exschool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exschool.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exschool.exsname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exschool.exsid
     *
     * @return the value of exschool.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exschool.exsid
     *
     * @param exsid the value for exschool.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exschool.exsname
     *
     * @return the value of exschool.exsname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExsname() {
        return exsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exschool.exsname
     *
     * @param exsname the value for exschool.exsname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsname(String exsname) {
        this.exsname = exsname;
    }
}