package com.TestExa.boot.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExstudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public ExstudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andExstuidIsNull() {
            addCriterion("exstuid is null");
            return (Criteria) this;
        }

        public Criteria andExstuidIsNotNull() {
            addCriterion("exstuid is not null");
            return (Criteria) this;
        }

        public Criteria andExstuidEqualTo(Integer value) {
            addCriterion("exstuid =", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidNotEqualTo(Integer value) {
            addCriterion("exstuid <>", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidGreaterThan(Integer value) {
            addCriterion("exstuid >", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exstuid >=", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidLessThan(Integer value) {
            addCriterion("exstuid <", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidLessThanOrEqualTo(Integer value) {
            addCriterion("exstuid <=", value, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidIn(List<Integer> values) {
            addCriterion("exstuid in", values, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidNotIn(List<Integer> values) {
            addCriterion("exstuid not in", values, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidBetween(Integer value1, Integer value2) {
            addCriterion("exstuid between", value1, value2, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstuidNotBetween(Integer value1, Integer value2) {
            addCriterion("exstuid not between", value1, value2, "exstuid");
            return (Criteria) this;
        }

        public Criteria andExstunumberIsNull() {
            addCriterion("exstunumber is null");
            return (Criteria) this;
        }

        public Criteria andExstunumberIsNotNull() {
            addCriterion("exstunumber is not null");
            return (Criteria) this;
        }

        public Criteria andExstunumberEqualTo(Integer value) {
            addCriterion("exstunumber =", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberNotEqualTo(Integer value) {
            addCriterion("exstunumber <>", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberGreaterThan(Integer value) {
            addCriterion("exstunumber >", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("exstunumber >=", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberLessThan(Integer value) {
            addCriterion("exstunumber <", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberLessThanOrEqualTo(Integer value) {
            addCriterion("exstunumber <=", value, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberIn(List<Integer> values) {
            addCriterion("exstunumber in", values, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberNotIn(List<Integer> values) {
            addCriterion("exstunumber not in", values, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberBetween(Integer value1, Integer value2) {
            addCriterion("exstunumber between", value1, value2, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunumberNotBetween(Integer value1, Integer value2) {
            addCriterion("exstunumber not between", value1, value2, "exstunumber");
            return (Criteria) this;
        }

        public Criteria andExstunameIsNull() {
            addCriterion("exstuname is null");
            return (Criteria) this;
        }

        public Criteria andExstunameIsNotNull() {
            addCriterion("exstuname is not null");
            return (Criteria) this;
        }

        public Criteria andExstunameEqualTo(String value) {
            addCriterion("exstuname =", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameNotEqualTo(String value) {
            addCriterion("exstuname <>", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameGreaterThan(String value) {
            addCriterion("exstuname >", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameGreaterThanOrEqualTo(String value) {
            addCriterion("exstuname >=", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameLessThan(String value) {
            addCriterion("exstuname <", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameLessThanOrEqualTo(String value) {
            addCriterion("exstuname <=", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameLike(String value) {
            addCriterion("exstuname like", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameNotLike(String value) {
            addCriterion("exstuname not like", value, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameIn(List<String> values) {
            addCriterion("exstuname in", values, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameNotIn(List<String> values) {
            addCriterion("exstuname not in", values, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameBetween(String value1, String value2) {
            addCriterion("exstuname between", value1, value2, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstunameNotBetween(String value1, String value2) {
            addCriterion("exstuname not between", value1, value2, "exstuname");
            return (Criteria) this;
        }

        public Criteria andExstupwdIsNull() {
            addCriterion("exstupwd is null");
            return (Criteria) this;
        }

        public Criteria andExstupwdIsNotNull() {
            addCriterion("exstupwd is not null");
            return (Criteria) this;
        }

        public Criteria andExstupwdEqualTo(String value) {
            addCriterion("exstupwd =", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdNotEqualTo(String value) {
            addCriterion("exstupwd <>", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdGreaterThan(String value) {
            addCriterion("exstupwd >", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdGreaterThanOrEqualTo(String value) {
            addCriterion("exstupwd >=", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdLessThan(String value) {
            addCriterion("exstupwd <", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdLessThanOrEqualTo(String value) {
            addCriterion("exstupwd <=", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdLike(String value) {
            addCriterion("exstupwd like", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdNotLike(String value) {
            addCriterion("exstupwd not like", value, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdIn(List<String> values) {
            addCriterion("exstupwd in", values, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdNotIn(List<String> values) {
            addCriterion("exstupwd not in", values, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdBetween(String value1, String value2) {
            addCriterion("exstupwd between", value1, value2, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstupwdNotBetween(String value1, String value2) {
            addCriterion("exstupwd not between", value1, value2, "exstupwd");
            return (Criteria) this;
        }

        public Criteria andExstusexIsNull() {
            addCriterion("exstusex is null");
            return (Criteria) this;
        }

        public Criteria andExstusexIsNotNull() {
            addCriterion("exstusex is not null");
            return (Criteria) this;
        }

        public Criteria andExstusexEqualTo(String value) {
            addCriterion("exstusex =", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexNotEqualTo(String value) {
            addCriterion("exstusex <>", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexGreaterThan(String value) {
            addCriterion("exstusex >", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexGreaterThanOrEqualTo(String value) {
            addCriterion("exstusex >=", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexLessThan(String value) {
            addCriterion("exstusex <", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexLessThanOrEqualTo(String value) {
            addCriterion("exstusex <=", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexLike(String value) {
            addCriterion("exstusex like", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexNotLike(String value) {
            addCriterion("exstusex not like", value, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexIn(List<String> values) {
            addCriterion("exstusex in", values, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexNotIn(List<String> values) {
            addCriterion("exstusex not in", values, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexBetween(String value1, String value2) {
            addCriterion("exstusex between", value1, value2, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstusexNotBetween(String value1, String value2) {
            addCriterion("exstusex not between", value1, value2, "exstusex");
            return (Criteria) this;
        }

        public Criteria andExstubirthIsNull() {
            addCriterion("exstubirth is null");
            return (Criteria) this;
        }

        public Criteria andExstubirthIsNotNull() {
            addCriterion("exstubirth is not null");
            return (Criteria) this;
        }

        public Criteria andExstubirthEqualTo(Date value) {
            addCriterionForJDBCDate("exstubirth =", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("exstubirth <>", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthGreaterThan(Date value) {
            addCriterionForJDBCDate("exstubirth >", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exstubirth >=", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthLessThan(Date value) {
            addCriterionForJDBCDate("exstubirth <", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("exstubirth <=", value, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthIn(List<Date> values) {
            addCriterionForJDBCDate("exstubirth in", values, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("exstubirth not in", values, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exstubirth between", value1, value2, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstubirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("exstubirth not between", value1, value2, "exstubirth");
            return (Criteria) this;
        }

        public Criteria andExstutelIsNull() {
            addCriterion("exstutel is null");
            return (Criteria) this;
        }

        public Criteria andExstutelIsNotNull() {
            addCriterion("exstutel is not null");
            return (Criteria) this;
        }

        public Criteria andExstutelEqualTo(String value) {
            addCriterion("exstutel =", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelNotEqualTo(String value) {
            addCriterion("exstutel <>", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelGreaterThan(String value) {
            addCriterion("exstutel >", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelGreaterThanOrEqualTo(String value) {
            addCriterion("exstutel >=", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelLessThan(String value) {
            addCriterion("exstutel <", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelLessThanOrEqualTo(String value) {
            addCriterion("exstutel <=", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelLike(String value) {
            addCriterion("exstutel like", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelNotLike(String value) {
            addCriterion("exstutel not like", value, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelIn(List<String> values) {
            addCriterion("exstutel in", values, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelNotIn(List<String> values) {
            addCriterion("exstutel not in", values, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelBetween(String value1, String value2) {
            addCriterion("exstutel between", value1, value2, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstutelNotBetween(String value1, String value2) {
            addCriterion("exstutel not between", value1, value2, "exstutel");
            return (Criteria) this;
        }

        public Criteria andExstuqqIsNull() {
            addCriterion("exstuqq is null");
            return (Criteria) this;
        }

        public Criteria andExstuqqIsNotNull() {
            addCriterion("exstuqq is not null");
            return (Criteria) this;
        }

        public Criteria andExstuqqEqualTo(String value) {
            addCriterion("exstuqq =", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqNotEqualTo(String value) {
            addCriterion("exstuqq <>", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqGreaterThan(String value) {
            addCriterion("exstuqq >", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqGreaterThanOrEqualTo(String value) {
            addCriterion("exstuqq >=", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqLessThan(String value) {
            addCriterion("exstuqq <", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqLessThanOrEqualTo(String value) {
            addCriterion("exstuqq <=", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqLike(String value) {
            addCriterion("exstuqq like", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqNotLike(String value) {
            addCriterion("exstuqq not like", value, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqIn(List<String> values) {
            addCriterion("exstuqq in", values, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqNotIn(List<String> values) {
            addCriterion("exstuqq not in", values, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqBetween(String value1, String value2) {
            addCriterion("exstuqq between", value1, value2, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuqqNotBetween(String value1, String value2) {
            addCriterion("exstuqq not between", value1, value2, "exstuqq");
            return (Criteria) this;
        }

        public Criteria andExstuemailIsNull() {
            addCriterion("exstuemail is null");
            return (Criteria) this;
        }

        public Criteria andExstuemailIsNotNull() {
            addCriterion("exstuemail is not null");
            return (Criteria) this;
        }

        public Criteria andExstuemailEqualTo(String value) {
            addCriterion("exstuemail =", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailNotEqualTo(String value) {
            addCriterion("exstuemail <>", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailGreaterThan(String value) {
            addCriterion("exstuemail >", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailGreaterThanOrEqualTo(String value) {
            addCriterion("exstuemail >=", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailLessThan(String value) {
            addCriterion("exstuemail <", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailLessThanOrEqualTo(String value) {
            addCriterion("exstuemail <=", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailLike(String value) {
            addCriterion("exstuemail like", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailNotLike(String value) {
            addCriterion("exstuemail not like", value, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailIn(List<String> values) {
            addCriterion("exstuemail in", values, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailNotIn(List<String> values) {
            addCriterion("exstuemail not in", values, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailBetween(String value1, String value2) {
            addCriterion("exstuemail between", value1, value2, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuemailNotBetween(String value1, String value2) {
            addCriterion("exstuemail not between", value1, value2, "exstuemail");
            return (Criteria) this;
        }

        public Criteria andExstuaddrIsNull() {
            addCriterion("exstuaddr is null");
            return (Criteria) this;
        }

        public Criteria andExstuaddrIsNotNull() {
            addCriterion("exstuaddr is not null");
            return (Criteria) this;
        }

        public Criteria andExstuaddrEqualTo(String value) {
            addCriterion("exstuaddr =", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrNotEqualTo(String value) {
            addCriterion("exstuaddr <>", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrGreaterThan(String value) {
            addCriterion("exstuaddr >", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrGreaterThanOrEqualTo(String value) {
            addCriterion("exstuaddr >=", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrLessThan(String value) {
            addCriterion("exstuaddr <", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrLessThanOrEqualTo(String value) {
            addCriterion("exstuaddr <=", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrLike(String value) {
            addCriterion("exstuaddr like", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrNotLike(String value) {
            addCriterion("exstuaddr not like", value, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrIn(List<String> values) {
            addCriterion("exstuaddr in", values, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrNotIn(List<String> values) {
            addCriterion("exstuaddr not in", values, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrBetween(String value1, String value2) {
            addCriterion("exstuaddr between", value1, value2, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExstuaddrNotBetween(String value1, String value2) {
            addCriterion("exstuaddr not between", value1, value2, "exstuaddr");
            return (Criteria) this;
        }

        public Criteria andExsidIsNull() {
            addCriterion("exsid is null");
            return (Criteria) this;
        }

        public Criteria andExsidIsNotNull() {
            addCriterion("exsid is not null");
            return (Criteria) this;
        }

        public Criteria andExsidEqualTo(Integer value) {
            addCriterion("exsid =", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotEqualTo(Integer value) {
            addCriterion("exsid <>", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThan(Integer value) {
            addCriterion("exsid >", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exsid >=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThan(Integer value) {
            addCriterion("exsid <", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThanOrEqualTo(Integer value) {
            addCriterion("exsid <=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidIn(List<Integer> values) {
            addCriterion("exsid in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotIn(List<Integer> values) {
            addCriterion("exsid not in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidBetween(Integer value1, Integer value2) {
            addCriterion("exsid between", value1, value2, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotBetween(Integer value1, Integer value2) {
            addCriterion("exsid not between", value1, value2, "exsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exstudent
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exstudent
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}