package com.TestExa.boot.vo;

import java.util.Date;

public class Exstudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exstuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstunumber
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exstunumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstuname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstupwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstupwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstusex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstusex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstubirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exstubirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstutel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstutel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstuqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstuqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstuemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstuemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exstuaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exstuaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exstudent.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstuid
     *
     * @return the value of exstudent.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExstuid() {
        return exstuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstuid
     *
     * @param exstuid the value for exstudent.exstuid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuid(Integer exstuid) {
        this.exstuid = exstuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstunumber
     *
     * @return the value of exstudent.exstunumber
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExstunumber() {
        return exstunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstunumber
     *
     * @param exstunumber the value for exstudent.exstunumber
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstunumber(Integer exstunumber) {
        this.exstunumber = exstunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstuname
     *
     * @return the value of exstudent.exstuname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstuname() {
        return exstuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstuname
     *
     * @param exstuname the value for exstudent.exstuname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuname(String exstuname) {
        this.exstuname = exstuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstupwd
     *
     * @return the value of exstudent.exstupwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstupwd() {
        return exstupwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstupwd
     *
     * @param exstupwd the value for exstudent.exstupwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstupwd(String exstupwd) {
        this.exstupwd = exstupwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstusex
     *
     * @return the value of exstudent.exstusex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstusex() {
        return exstusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstusex
     *
     * @param exstusex the value for exstudent.exstusex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstusex(String exstusex) {
        this.exstusex = exstusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstubirth
     *
     * @return the value of exstudent.exstubirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExstubirth() {
        return exstubirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstubirth
     *
     * @param exstubirth the value for exstudent.exstubirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstubirth(Date exstubirth) {
        this.exstubirth = exstubirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstutel
     *
     * @return the value of exstudent.exstutel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstutel() {
        return exstutel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstutel
     *
     * @param exstutel the value for exstudent.exstutel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstutel(String exstutel) {
        this.exstutel = exstutel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstuqq
     *
     * @return the value of exstudent.exstuqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstuqq() {
        return exstuqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstuqq
     *
     * @param exstuqq the value for exstudent.exstuqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuqq(String exstuqq) {
        this.exstuqq = exstuqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstuemail
     *
     * @return the value of exstudent.exstuemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstuemail() {
        return exstuemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstuemail
     *
     * @param exstuemail the value for exstudent.exstuemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuemail(String exstuemail) {
        this.exstuemail = exstuemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exstuaddr
     *
     * @return the value of exstudent.exstuaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExstuaddr() {
        return exstuaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exstuaddr
     *
     * @param exstuaddr the value for exstudent.exstuaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExstuaddr(String exstuaddr) {
        this.exstuaddr = exstuaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exstudent.exsid
     *
     * @return the value of exstudent.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exstudent.exsid
     *
     * @param exsid the value for exstudent.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }
}