package com.TestExa.boot.vo;

import java.util.Date;

public class Exsubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exsubject.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsubid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exsubject.exsubname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exsubname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exsubject.exsubtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date exsubtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exsubject.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exsubject.exsubid
     *
     * @return the value of exsubject.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsubid() {
        return exsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exsubject.exsubid
     *
     * @param exsubid the value for exsubject.exsubid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsubid(Integer exsubid) {
        this.exsubid = exsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exsubject.exsubname
     *
     * @return the value of exsubject.exsubname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExsubname() {
        return exsubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exsubject.exsubname
     *
     * @param exsubname the value for exsubject.exsubname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsubname(String exsubname) {
        this.exsubname = exsubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exsubject.exsubtime
     *
     * @return the value of exsubject.exsubtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExsubtime() {
        return exsubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exsubject.exsubtime
     *
     * @param exsubtime the value for exsubject.exsubtime
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsubtime(Date exsubtime) {
        this.exsubtime = exsubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exsubject.exsid
     *
     * @return the value of exsubject.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exsubject.exsid
     *
     * @param exsid the value for exsubject.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }
}