package com.TestExa.boot.vo;

import java.util.Date;

public class Exteacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer extid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extpwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extsex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extbirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date extbirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.exttel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String exttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.extaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exteacher.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extid
     *
     * @return the value of exteacher.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExtid() {
        return extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extid
     *
     * @param extid the value for exteacher.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtid(Integer extid) {
        this.extid = extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extname
     *
     * @return the value of exteacher.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtname() {
        return extname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extname
     *
     * @param extname the value for exteacher.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtname(String extname) {
        this.extname = extname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extpwd
     *
     * @return the value of exteacher.extpwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtpwd() {
        return extpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extpwd
     *
     * @param extpwd the value for exteacher.extpwd
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtpwd(String extpwd) {
        this.extpwd = extpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extsex
     *
     * @return the value of exteacher.extsex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtsex() {
        return extsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extsex
     *
     * @param extsex the value for exteacher.extsex
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtsex(String extsex) {
        this.extsex = extsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extbirth
     *
     * @return the value of exteacher.extbirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExtbirth() {
        return extbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extbirth
     *
     * @param extbirth the value for exteacher.extbirth
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtbirth(Date extbirth) {
        this.extbirth = extbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.exttel
     *
     * @return the value of exteacher.exttel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExttel() {
        return exttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.exttel
     *
     * @param exttel the value for exteacher.exttel
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExttel(String exttel) {
        this.exttel = exttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extqq
     *
     * @return the value of exteacher.extqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtqq() {
        return extqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extqq
     *
     * @param extqq the value for exteacher.extqq
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtqq(String extqq) {
        this.extqq = extqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extemail
     *
     * @return the value of exteacher.extemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtemail() {
        return extemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extemail
     *
     * @param extemail the value for exteacher.extemail
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtemail(String extemail) {
        this.extemail = extemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.extaddr
     *
     * @return the value of exteacher.extaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtaddr() {
        return extaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.extaddr
     *
     * @param extaddr the value for exteacher.extaddr
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtaddr(String extaddr) {
        this.extaddr = extaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exteacher.exsid
     *
     * @return the value of exteacher.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExsid() {
        return exsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exteacher.exsid
     *
     * @param exsid the value for exteacher.exsid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExsid(Integer exsid) {
        this.exsid = exsid;
    }
}