package com.TestExa.boot.vo;

import java.util.Date;

public class Exterm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exterm.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer exteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exterm.extbegin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date extbegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exterm.extend
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Date extend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exterm.exteid
     *
     * @return the value of exterm.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExteid() {
        return exteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exterm.exteid
     *
     * @param exteid the value for exterm.exteid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExteid(Integer exteid) {
        this.exteid = exteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exterm.extbegin
     *
     * @return the value of exterm.extbegin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExtbegin() {
        return extbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exterm.extbegin
     *
     * @param extbegin the value for exterm.extbegin
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtbegin(Date extbegin) {
        this.extbegin = extbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exterm.extend
     *
     * @return the value of exterm.extend
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Date getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exterm.extend
     *
     * @param extend the value for exterm.extend
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtend(Date extend) {
        this.extend = extend;
    }
}