package com.TestExa.boot.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExteacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public ExteacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andExtidIsNull() {
            addCriterion("extid is null");
            return (Criteria) this;
        }

        public Criteria andExtidIsNotNull() {
            addCriterion("extid is not null");
            return (Criteria) this;
        }

        public Criteria andExtidEqualTo(Integer value) {
            addCriterion("extid =", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidNotEqualTo(Integer value) {
            addCriterion("extid <>", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidGreaterThan(Integer value) {
            addCriterion("extid >", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("extid >=", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidLessThan(Integer value) {
            addCriterion("extid <", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidLessThanOrEqualTo(Integer value) {
            addCriterion("extid <=", value, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidIn(List<Integer> values) {
            addCriterion("extid in", values, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidNotIn(List<Integer> values) {
            addCriterion("extid not in", values, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidBetween(Integer value1, Integer value2) {
            addCriterion("extid between", value1, value2, "extid");
            return (Criteria) this;
        }

        public Criteria andExtidNotBetween(Integer value1, Integer value2) {
            addCriterion("extid not between", value1, value2, "extid");
            return (Criteria) this;
        }

        public Criteria andExtnameIsNull() {
            addCriterion("extname is null");
            return (Criteria) this;
        }

        public Criteria andExtnameIsNotNull() {
            addCriterion("extname is not null");
            return (Criteria) this;
        }

        public Criteria andExtnameEqualTo(String value) {
            addCriterion("extname =", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameNotEqualTo(String value) {
            addCriterion("extname <>", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameGreaterThan(String value) {
            addCriterion("extname >", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameGreaterThanOrEqualTo(String value) {
            addCriterion("extname >=", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameLessThan(String value) {
            addCriterion("extname <", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameLessThanOrEqualTo(String value) {
            addCriterion("extname <=", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameLike(String value) {
            addCriterion("extname like", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameNotLike(String value) {
            addCriterion("extname not like", value, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameIn(List<String> values) {
            addCriterion("extname in", values, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameNotIn(List<String> values) {
            addCriterion("extname not in", values, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameBetween(String value1, String value2) {
            addCriterion("extname between", value1, value2, "extname");
            return (Criteria) this;
        }

        public Criteria andExtnameNotBetween(String value1, String value2) {
            addCriterion("extname not between", value1, value2, "extname");
            return (Criteria) this;
        }

        public Criteria andExtpwdIsNull() {
            addCriterion("extpwd is null");
            return (Criteria) this;
        }

        public Criteria andExtpwdIsNotNull() {
            addCriterion("extpwd is not null");
            return (Criteria) this;
        }

        public Criteria andExtpwdEqualTo(String value) {
            addCriterion("extpwd =", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdNotEqualTo(String value) {
            addCriterion("extpwd <>", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdGreaterThan(String value) {
            addCriterion("extpwd >", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdGreaterThanOrEqualTo(String value) {
            addCriterion("extpwd >=", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdLessThan(String value) {
            addCriterion("extpwd <", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdLessThanOrEqualTo(String value) {
            addCriterion("extpwd <=", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdLike(String value) {
            addCriterion("extpwd like", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdNotLike(String value) {
            addCriterion("extpwd not like", value, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdIn(List<String> values) {
            addCriterion("extpwd in", values, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdNotIn(List<String> values) {
            addCriterion("extpwd not in", values, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdBetween(String value1, String value2) {
            addCriterion("extpwd between", value1, value2, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtpwdNotBetween(String value1, String value2) {
            addCriterion("extpwd not between", value1, value2, "extpwd");
            return (Criteria) this;
        }

        public Criteria andExtsexIsNull() {
            addCriterion("extsex is null");
            return (Criteria) this;
        }

        public Criteria andExtsexIsNotNull() {
            addCriterion("extsex is not null");
            return (Criteria) this;
        }

        public Criteria andExtsexEqualTo(String value) {
            addCriterion("extsex =", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexNotEqualTo(String value) {
            addCriterion("extsex <>", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexGreaterThan(String value) {
            addCriterion("extsex >", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexGreaterThanOrEqualTo(String value) {
            addCriterion("extsex >=", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexLessThan(String value) {
            addCriterion("extsex <", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexLessThanOrEqualTo(String value) {
            addCriterion("extsex <=", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexLike(String value) {
            addCriterion("extsex like", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexNotLike(String value) {
            addCriterion("extsex not like", value, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexIn(List<String> values) {
            addCriterion("extsex in", values, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexNotIn(List<String> values) {
            addCriterion("extsex not in", values, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexBetween(String value1, String value2) {
            addCriterion("extsex between", value1, value2, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtsexNotBetween(String value1, String value2) {
            addCriterion("extsex not between", value1, value2, "extsex");
            return (Criteria) this;
        }

        public Criteria andExtbirthIsNull() {
            addCriterion("extbirth is null");
            return (Criteria) this;
        }

        public Criteria andExtbirthIsNotNull() {
            addCriterion("extbirth is not null");
            return (Criteria) this;
        }

        public Criteria andExtbirthEqualTo(Date value) {
            addCriterionForJDBCDate("extbirth =", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("extbirth <>", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthGreaterThan(Date value) {
            addCriterionForJDBCDate("extbirth >", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("extbirth >=", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthLessThan(Date value) {
            addCriterionForJDBCDate("extbirth <", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("extbirth <=", value, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthIn(List<Date> values) {
            addCriterionForJDBCDate("extbirth in", values, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("extbirth not in", values, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("extbirth between", value1, value2, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExtbirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("extbirth not between", value1, value2, "extbirth");
            return (Criteria) this;
        }

        public Criteria andExttelIsNull() {
            addCriterion("exttel is null");
            return (Criteria) this;
        }

        public Criteria andExttelIsNotNull() {
            addCriterion("exttel is not null");
            return (Criteria) this;
        }

        public Criteria andExttelEqualTo(String value) {
            addCriterion("exttel =", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelNotEqualTo(String value) {
            addCriterion("exttel <>", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelGreaterThan(String value) {
            addCriterion("exttel >", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelGreaterThanOrEqualTo(String value) {
            addCriterion("exttel >=", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelLessThan(String value) {
            addCriterion("exttel <", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelLessThanOrEqualTo(String value) {
            addCriterion("exttel <=", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelLike(String value) {
            addCriterion("exttel like", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelNotLike(String value) {
            addCriterion("exttel not like", value, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelIn(List<String> values) {
            addCriterion("exttel in", values, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelNotIn(List<String> values) {
            addCriterion("exttel not in", values, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelBetween(String value1, String value2) {
            addCriterion("exttel between", value1, value2, "exttel");
            return (Criteria) this;
        }

        public Criteria andExttelNotBetween(String value1, String value2) {
            addCriterion("exttel not between", value1, value2, "exttel");
            return (Criteria) this;
        }

        public Criteria andExtqqIsNull() {
            addCriterion("extqq is null");
            return (Criteria) this;
        }

        public Criteria andExtqqIsNotNull() {
            addCriterion("extqq is not null");
            return (Criteria) this;
        }

        public Criteria andExtqqEqualTo(String value) {
            addCriterion("extqq =", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqNotEqualTo(String value) {
            addCriterion("extqq <>", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqGreaterThan(String value) {
            addCriterion("extqq >", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqGreaterThanOrEqualTo(String value) {
            addCriterion("extqq >=", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqLessThan(String value) {
            addCriterion("extqq <", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqLessThanOrEqualTo(String value) {
            addCriterion("extqq <=", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqLike(String value) {
            addCriterion("extqq like", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqNotLike(String value) {
            addCriterion("extqq not like", value, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqIn(List<String> values) {
            addCriterion("extqq in", values, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqNotIn(List<String> values) {
            addCriterion("extqq not in", values, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqBetween(String value1, String value2) {
            addCriterion("extqq between", value1, value2, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtqqNotBetween(String value1, String value2) {
            addCriterion("extqq not between", value1, value2, "extqq");
            return (Criteria) this;
        }

        public Criteria andExtemailIsNull() {
            addCriterion("extemail is null");
            return (Criteria) this;
        }

        public Criteria andExtemailIsNotNull() {
            addCriterion("extemail is not null");
            return (Criteria) this;
        }

        public Criteria andExtemailEqualTo(String value) {
            addCriterion("extemail =", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailNotEqualTo(String value) {
            addCriterion("extemail <>", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailGreaterThan(String value) {
            addCriterion("extemail >", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailGreaterThanOrEqualTo(String value) {
            addCriterion("extemail >=", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailLessThan(String value) {
            addCriterion("extemail <", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailLessThanOrEqualTo(String value) {
            addCriterion("extemail <=", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailLike(String value) {
            addCriterion("extemail like", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailNotLike(String value) {
            addCriterion("extemail not like", value, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailIn(List<String> values) {
            addCriterion("extemail in", values, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailNotIn(List<String> values) {
            addCriterion("extemail not in", values, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailBetween(String value1, String value2) {
            addCriterion("extemail between", value1, value2, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtemailNotBetween(String value1, String value2) {
            addCriterion("extemail not between", value1, value2, "extemail");
            return (Criteria) this;
        }

        public Criteria andExtaddrIsNull() {
            addCriterion("extaddr is null");
            return (Criteria) this;
        }

        public Criteria andExtaddrIsNotNull() {
            addCriterion("extaddr is not null");
            return (Criteria) this;
        }

        public Criteria andExtaddrEqualTo(String value) {
            addCriterion("extaddr =", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrNotEqualTo(String value) {
            addCriterion("extaddr <>", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrGreaterThan(String value) {
            addCriterion("extaddr >", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrGreaterThanOrEqualTo(String value) {
            addCriterion("extaddr >=", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrLessThan(String value) {
            addCriterion("extaddr <", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrLessThanOrEqualTo(String value) {
            addCriterion("extaddr <=", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrLike(String value) {
            addCriterion("extaddr like", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrNotLike(String value) {
            addCriterion("extaddr not like", value, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrIn(List<String> values) {
            addCriterion("extaddr in", values, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrNotIn(List<String> values) {
            addCriterion("extaddr not in", values, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrBetween(String value1, String value2) {
            addCriterion("extaddr between", value1, value2, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExtaddrNotBetween(String value1, String value2) {
            addCriterion("extaddr not between", value1, value2, "extaddr");
            return (Criteria) this;
        }

        public Criteria andExsidIsNull() {
            addCriterion("exsid is null");
            return (Criteria) this;
        }

        public Criteria andExsidIsNotNull() {
            addCriterion("exsid is not null");
            return (Criteria) this;
        }

        public Criteria andExsidEqualTo(Integer value) {
            addCriterion("exsid =", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotEqualTo(Integer value) {
            addCriterion("exsid <>", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThan(Integer value) {
            addCriterion("exsid >", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("exsid >=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThan(Integer value) {
            addCriterion("exsid <", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidLessThanOrEqualTo(Integer value) {
            addCriterion("exsid <=", value, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidIn(List<Integer> values) {
            addCriterion("exsid in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotIn(List<Integer> values) {
            addCriterion("exsid not in", values, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidBetween(Integer value1, Integer value2) {
            addCriterion("exsid between", value1, value2, "exsid");
            return (Criteria) this;
        }

        public Criteria andExsidNotBetween(Integer value1, Integer value2) {
            addCriterion("exsid not between", value1, value2, "exsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exteacher
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exteacher
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}