package com.TestExa.boot.vo;

public class Extype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column extype.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private Integer extid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column extype.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    private String extname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extype.extid
     *
     * @return the value of extype.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public Integer getExtid() {
        return extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extype.extid
     *
     * @param extid the value for extype.extid
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtid(Integer extid) {
        this.extid = extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extype.extname
     *
     * @return the value of extype.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public String getExtname() {
        return extname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extype.extname
     *
     * @param extname the value for extype.extname
     *
     * @mbg.generated Sat Oct 06 10:45:40 CST 2018
     */
    public void setExtname(String extname) {
        this.extname = extname;
    }
}